import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// initial state for slice
interface CounterState {
  value: number;
}

const initialState: CounterState = {
  value: 0,
};

// slice of the store
const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    increment(state) {
      state.value += 1;
    },
    decrement(state) {
      state.value -= 1;
    },
    reset(state) {
      state.value = 0;
    },
    setCounter(state, action: PayloadAction<number>) {
      state.value = action.payload;
    },
  },
});

// action creators generated by slice
export const { increment, decrement, reset, setCounter } = counterSlice.actions;

// reducer functions generated by the slice
export default counterSlice.reducer;
